
services:
  server:
      build: 
        context: .  
        dockerfile: Dockerfile
      ports:
        - '3000:3000'
      # environment:
      #   - DATABASE_URL="postgresql://postgres:root@host.docker.internal:5432/monlivre?schema=public"
      env_file:
        - .env.prod
      extra_hosts:
        - "host.docker.internal:host-gateway"
